language: java

script: 
  - mvn -e verify

after_success:
  - mvn clean test jacoco:report coveralls:report

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  fast_finish: true
  allow_failures:
    - jdk: oraclejdk8
