language: java

sudo: false

before_install:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
         wget --no-check-certificate https://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip;
         unzip -qq apache-maven-3.3.9-bin.zip;
         export M2_HOME=$PWD/apache-maven-3.3.9;
         export PATH=$M2_HOME/bin:$PATH;
     fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
         brew update --quiet;
         brew upgrade maven;
     fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$JVM" == "latest" ]; then
         brew tap caskroom/cask;
         brew install Caskroom/cask/java;
     fi
   - echo $JAVA_HOME
# requires sudo
#  - java -Xshare:dump

install:
  # install without any testing to get dependencies in place
  - mvn install -Dmaven.test.skip=true -B -V -fae -T2

script:
  # execute unit and integration tests
  - mvn -e -fae -B -Dfailsafe.useFile=false -T2 clean test verify
  - if [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
         mvn javadoc:javadoc;
         mvn javadoc:test-javadoc;
    fi

after_success:
  # generate code coverage report
  - mvn -B -e -fae -Ptravis-ci clean verify jacoco:report coveralls:report

os:
  - linux
  - osx

matrix:
  fast_finish: true
  include:
    # additional builds
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
    - os: osx
      env: JVM=latest
# these are the current Travis default JDKs on linux/osx
#    - os: linux
#      jdk: oraclejdk7
#    - os: osx
#      env: JAVA_HOME=/usr/libexec/java_home
  allow_failures:
    - env: JAVA_HOME=/usr/lib/jvm/java-7-oracle

cache:
  brew: true
  directories:
  - $HOME/.m2
  #- /Library/Caches/Homebrew
