language: java

sudo: false

before_install:
#  - unset GEM_PATH
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
   - mvn --version

install:
  # install without any testing
  - mvn install -U -Dmaven.test.skip=true -B -V -fae -q -T2

script:
  # execute tests
  - mvn -e verify -B

after_success:
  # generate code coverage report
  - mvn -B -e -fae -Ptravis-ci clean verify jacoco:report coveralls:report

# jdk:
#  - openjdk7
#  - oraclejdk7
#  - oraclejdk8

os:
  - linux
  - osx

matrix:
  - os: linux
    # nothing special
  - os: osx
    env: JAVA_HOME=/usr/libexec/java_home

cache:
  directories:
  - $HOME/.m2
