language: java

before_install:
  - unset GEM_PATH

install:
  # install without testing
  - mvn install -Dmaven.test.skip=true -B -V -fae -q

script:
  # execute tests
  - mvn -e verify -B

after_success:
  # generate code coverage report
  - mvn -B -e -fae -Ptravis-ci clean verify jacoco:report coveralls:report

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

os:
  - linux
  # - osx

matrix:
  fast_finish: true

cache:
  directories:
  - cache
