init:
  - git config --global core.autocrlf true
  - git config --global core.safecrlf true

clone_folder: C:\projects\sass-maven-plugin

# can't use shallow clone because we need to convert line endings in test expectations
shallow_clone: false

version: "{build} ({branch})"

skip_tags: true

branches:
  except:
    - gh-pages

install:
  - set PATH=%PATH%;C:\bin\apache-maven-3.2.3\bin
  - set MVN_VERSION=3.2.3
  - IF NOT exist "C:\bin\apache-maven-%MVN_VERSION%\bin\*.*" (echo Maven %MVN_VERSION% not installed, so install it & cinst maven -Version %MVN_VERSION%) ELSE (echo  Maven %MVN_VERSION% already installed)
  - cd C:\projects\sass-maven-plugin
  - mvn install -Dmaven.test.skip=true -B -V -fae -q -T2

build: off

test_script:
  - cd C:\projects\sass-maven-plugin
  - mvn -e verify -fae -B

environment:
  
  matrix:
    - myEnv: JDK7
      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - myEnv: JDK8
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: false

cache:
  - C:\bin\apache-maven-3.2.3
  - C:\Users\appveyor\.m2\repository
